added helper scripts for step 6

diff --git a/tools/scripts/labdeploy b/tools/scripts/labdeploy
--- a/tools/scripts/labdeploy
+++ b/tools/scripts/labdeploy
@@ -1,6 +1,16 @@
 #! /bin/bash
 # set -x
 
+# Pretty error function
+die() {
+  printf '\n\033[0;31mERROR:\033[0m %s\n\n' "$*" >&2
+  exit 1
+}
+
+info() {
+  printf '\033[0;34mINFO:\033[0m %s\n' "$*"
+}
+
 BASE=$PROJECT_SOURCE
 LAB=$BASE/lab
 TOOLS=$BASE/tools
@@ -8,14 +18,25 @@ FF=$TOOLS/solution/steps
 
 # Return chapter details when no argument is passed (no chapter requested)
 if [ ! "$1" ]; then
-  echo "You need to provide the dir to run."
-  exit
+
+  # Exception case is step 6
+  STEP=$(< $TOOLS/scripts/current)
+
+  # For step 6 exception, run special case deploy
+  if [ $STEP -eq 6 ]; then
+
+    # Run special case deploy
+    source /projects/workshop/tools/scripts/step6/deploy
+
+    exit
+  fi
+
+  die "You need to provide a directory with sources to deploy."
 fi
 
 # to ensure all hidden files & dirs are deleted (.camel) we need to change directory and return
 if [ ! -d "$LAB/$1" ]; then
-  echo "The dir needs to exit in your 'lab' directory."
-  exit
+  die "The dir needs to exist in your 'lab' directory."
 fi
 
 
